# Generated by Django 4.2 on 2026-02-03 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bookingstatus',
                'db_table': 'events"."BookingStatus',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Event', max_length=255)),
                ('motive', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Event',
                'db_table': 'task_management"."Event',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(choices=[('fixed', 'Fixed'), ('unfixed', 'Unfixed')], default='unfixed', max_length=10)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holiday',
                'db_table': 'task_management"."Holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'rooms',
                'db_table': 'events"."Rooms',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tour',
                'db_table': 'events"."Tour',
                'ordering': ['-starting_date'],
            },
        ),
        migrations.CreateModel(
            name='tourmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tour')),
            ],
            options={
                'verbose_name': 'tourmember',
                'db_table': 'events"."tourmembers',
                'ordering': ['tour'],
                'unique_together': {('tour', 'member')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='member',
            field=models.ManyToManyField(related_name='members', through='events.tourmembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group Meeting')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.room')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.bookingstatus')),
            ],
            options={
                'verbose_name': 'Slot',
                'db_table': 'events"."Slots',
            },
        ),
    ]
