# Generated by Django 4.2 on 2026-02-03 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='bookslot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='SlotMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.bookslot')),
            ],
            options={
                'verbose_name': 'Slotmember',
                'db_table': 'events"."SlotMember',
                'ordering': ['slot'],
                'unique_together': {('slot', 'member')},
            },
        ),
        migrations.AddField(
            model_name='bookslot',
            name='members',
            field=models.ManyToManyField(through='events.SlotMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
