# Generated by Django 4.2 on 2026-02-04 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_holiday_date_alter_event_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='member',
        ),
        migrations.AddField(
            model_name='tour',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourcreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='members',
            field=models.ManyToManyField(related_name='tourmembers', through='events.tourmembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotcreater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotroom', to='events.room'),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotstatus', to='events.bookingstatus'),
        ),
        migrations.AlterField(
            model_name='slotmembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inslots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slotmembers',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotmembers', to='events.bookslot'),
        ),
        migrations.AlterField(
            model_name='tourmembers',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourmembers',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourmembers', to='events.tour'),
        ),
    ]
