# Generated by Django 4.2 on 2026-02-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_tour_member_tour_created_by_tour_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group Meeting')])),
                ('time', models.SmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meeting_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.room')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_management"."MeetingPush',
                'ordering': ['-created_at', 'is_active'],
            },
        ),
    ]
