# Generated by Django 4.2 on 2026-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookslot',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Slot'},
        ),
    ]
