# Generated by Django 4.2 on 2025-12-23 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='priority',
            fields=[
                ('priority_id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('priority_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('Status_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=50, unique=True, verbose_name='task_status')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='task_id')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None, max_length=500, verbose_name='task_description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_status_change', models.DateTimeField(default=None)),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('deadline', models.ForeignKey(db_column='deadline', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.priority')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.taskstatus', verbose_name='task_status')),
            ],
            options={
                'verbose_name': 'tasks',
                'db_table': 'task_management"."tasks',
            },
        ),
    ]
