# Generated by Django 4.2 on 2025-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=None, verbose_name='due_date'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='priority',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
