# Generated by Django 4.2 on 2025-12-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_remove_task_created_at_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreateAndEditLogs',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='edit_logs', serialize=False, to='task_management.task', verbose_name='task_id')),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_edit_time', models.TimeField(auto_now=True)),
                ('last_edit_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('status_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=50, unique=True, verbose_name='task_status')),
            ],
            options={
                'verbose_name': 'task_statuses',
                'db_table': 'task_management"."task_statuses',
            },
        ),
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('type_id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'task_types',
                'db_table': 'task_management"."task_types',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusChangeLogs',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status_change_log', serialize=False, to='task_management.task', verbose_name='task_id')),
                ('last_status_change_date', models.DateField(auto_now=True)),
                ('last_status_change_time', models.TimeField(auto_now=True)),
                ('status_change_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_log', to='task_management.taskstatus', verbose_name='change_to')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(db_column='current_status', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='task_management.taskstatus', verbose_name='task_status'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(db_column='task_type', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_type', to='task_management.tasktypes'),
            preserve_default=False,
        ),
    ]
