# Generated by Django 4.2 on 2025-12-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_taskcreateandeditlogs_taskstatus_tasktypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcreateandeditlogs',
            options={'verbose_name': 'task_edit_create_log'},
        ),
        migrations.AlterModelOptions(
            name='taskstatuschangelogs',
            options={'verbose_name': 'task_status_change_log'},
        ),
        migrations.AlterModelTable(
            name='taskcreateandeditlogs',
            table='Task_create_edit_logs',
        ),
        migrations.AlterModelTable(
            name='taskstatuschangelogs',
            table='Task_status_change_log',
        ),
    ]
