# Generated by Django 4.2 on 2025-12-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_alter_taskcreateandeditlogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskstatuschangelogs',
            name='status_change_to',
            field=models.ForeignKey(db_column='change_to', on_delete=django.db.models.deletion.CASCADE, related_name='status_change_log', to='task_management.taskstatus', verbose_name='change_to'),
        ),
        migrations.AlterField(
            model_name='tasktypes',
            name='type_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='taskstatuschangelogs',
            table='Task_status_changes_log',
        ),
    ]
