# Generated by Django 4.2 on 2026-01-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_taskstatus_status_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcreateandeditlogs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taskstatuschangelogs',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskcreateandeditlogs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskcreateandeditlogs',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='taskcreateandeditlogs',
            name='last_edit_date',
        ),
        migrations.RemoveField(
            model_name='taskcreateandeditlogs',
            name='last_edit_time',
        ),
        migrations.RemoveField(
            model_name='taskcreateandeditlogs',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskstatuschangelogs',
            name='last_status_change_date',
        ),
        migrations.RemoveField(
            model_name='taskstatuschangelogs',
            name='last_status_change_time',
        ),
        migrations.RemoveField(
            model_name='taskstatuschangelogs',
            name='status_change_to',
        ),
        migrations.RemoveField(
            model_name='taskstatuschangelogs',
            name='task',
        ),
        migrations.AddField(
            model_name='taskcreateandeditlogs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstatuschangelogs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='taskcreateandeditlogs',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taskstatuschangelogs',
            table=None,
        ),
    ]
