# Generated by Django 4.2 on 2026-01-02 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_management', '0006_alter_taskcreateandeditlogs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTasksCount',
            fields=[
                ('assignee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('count_sos', models.IntegerField(db_column='total_SOS', default=0)),
                ('count_1_Day', models.IntegerField(db_column='total_1_Day', default=0)),
                ('count_10_Day', models.IntegerField(db_column='total_10_Day', default=0)),
                ('count_Monthly', models.IntegerField(db_column='total_Monthly', default=0)),
                ('count_Quaterly', models.IntegerField(db_column='total_Quaterly', default=0)),
            ],
            options={
                'verbose_name': 'employee_tasks_count_by_type',
                'db_table': 'task_management"."employee_tasks_count_by_type',
                'ordering': ['-count_sos', '-count_1_Day'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='task_management.task')),
            ],
            options={
                'verbose_name': 'taskmessaging',
                'db_table': 'task_management"."taskmessaging',
                'ordering': ['-sender', '-created_at'],
            },
        ),
    ]
