# Generated by Django 4.2 on 2026-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_employeetaskscount_taskmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'task_status', 'verbose_name_plural': 'task_statuses'},
        ),
        migrations.AlterModelOptions(
            name='tasktypes',
            options={'verbose_name': 'task_type', 'verbose_name_plural': 'task_types'},
        ),
        migrations.AlterField(
            model_name='taskmessage',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
