# Generated by Django 4.2 on 2026-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_alter_task_options_alter_taskstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'taskmessaging'},
        ),
        migrations.RemoveField(
            model_name='taskmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='task_description'),
        ),
    ]
