# Generated by Django 4.2 on 2026-01-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0009_alter_taskmessage_options_remove_taskmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={'ordering': ['sender', '-created_at'], 'verbose_name': 'taskmessaging'},
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='sender',
            field=models.ForeignKey(db_column='sender', default='753', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
