# Generated by Django 4.2 on 2026-01-13 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0011_remove_task_assigned_to_taskassignies'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tasks', through='task_management.TaskAssignies', to=settings.AUTH_USER_MODEL),
        ),
    ]
