# Generated by Django 4.2 on 2026-01-14 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0012_task_assignees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_by'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskassignies',
            options={'ordering': ['task'], 'verbose_name': 'taskAssignee', 'verbose_name_plural': 'tasksAssignees'},
        ),
        migrations.AlterUniqueTogether(
            name='taskassignies',
            unique_together={('task', 'assigned_to')},
        ),
    ]
