# Generated by Django 4.2 on 2026-01-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task_management', '0013_alter_task_options_alter_taskassignies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedTasksCount',
            fields=[
                ('creator', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('count_sos', models.IntegerField(db_column='total_SOS', default=0)),
                ('count_1_Day', models.IntegerField(db_column='total_1_Day', default=0)),
                ('count_10_Day', models.IntegerField(db_column='total_10_Day', default=0)),
                ('count_Monthly', models.IntegerField(db_column='total_Monthly', default=0)),
                ('count_Quaterly', models.IntegerField(db_column='total_Quaterly', default=0)),
            ],
            options={
                'verbose_name': 'Created_tasks_count_by_type',
                'db_table': 'task_management"."Created_tasks_count_by_type',
                'ordering': ['-count_sos', '-count_1_Day'],
            },
        ),
        migrations.RenameModel(
            old_name='EmployeeTasksCount',
            new_name='AssingnedTasksCount',
        ),
        migrations.AlterModelOptions(
            name='assingnedtaskscount',
            options={'ordering': ['-count_sos', '-count_1_Day'], 'verbose_name': 'Assigned_tasks_count_by_type'},
        ),
        migrations.AlterModelTable(
            name='assingnedtaskscount',
            table='Assigned_tasks_count_by_type',
        ),
    ]
