# Generated by Django 4.2 on 2026-01-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0014_createdtaskscount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCreateAndEditLogs',
        ),
        migrations.DeleteModel(
            name='TaskStatusChangeLogs',
        ),
    ]
