# Generated by Django 4.2 on 2026-01-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0015_delete_taskcreateandeditlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreateAndEditLogs',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_edit_logs', serialize=False, to='task_management.task', verbose_name='task_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'task_edit_create_log',
                'db_table': 'task_management"."Task_create_edit_logs',
                'ordering': ['-last_edit'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusChangeLogs',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status_change_logs', serialize=False, to='task_management.task', verbose_name='task_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('status_change_to', models.ForeignKey(db_column='change_to', on_delete=django.db.models.deletion.CASCADE, related_name='status_change_log', to='task_management.taskstatus', verbose_name='change_to')),
            ],
            options={
                'verbose_name': 'task_status_change_log',
                'db_table': 'task_management"."Task_status_changes_log',
                'ordering': ['-last_edit'],
            },
        ),
    ]
