# Generated by Django 4.2 on 2026-02-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0016_taskcreateandeditlogs_taskstatuschangelogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assingnedtaskscount',
            options={'ordering': ['-count_SOS', '-count_1_Day'], 'verbose_name': 'Assigned_tasks_count_by_type'},
        ),
        migrations.AlterModelOptions(
            name='createdtaskscount',
            options={'ordering': ['-count_SOS', '-count_1_Day'], 'verbose_name': 'Created_tasks_count_by_type'},
        ),
        migrations.RenameField(
            model_name='assingnedtaskscount',
            old_name='count_sos',
            new_name='count_SOS',
        ),
        migrations.RenameField(
            model_name='createdtaskscount',
            old_name='count_sos',
            new_name='count_SOS',
        ),
    ]
