# Generated by Django 4.2 on 2026-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0017_alter_assingnedtaskscount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
