# Generated by Django 4.2 on 2026-02-10 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0018_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignies',
            name='assigned_to',
            field=models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.CASCADE, related_name='Tasks_assigned', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='taskassignies',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.task'),
        ),
    ]
