# Generated by Django 4.2 on 2026-02-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0019_alter_taskassignies_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_by'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
