# Generated by Django 4.2 on 2026-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0020_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.BigAutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='task_id'),
        ),
    ]
