# Generated by Django 4.2 on 2026-01-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_management', '0016_taskcreateandeditlogs_taskstatuschangelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Assettypes',
                'db_table': 'adminpanel"."Assettype',
            },
        ),
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Billcategories',
                'db_table': 'adminpanel"."Billcategory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('gst_number', models.CharField(max_length=50, unique=True)),
                ('office_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'db_table': 'adminpanel"."Vendor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('paid_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(db_column='current_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'db_table': 'adminpanel"."Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.billcategory')),
                ('status', models.ForeignKey(db_column='current_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus')),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'db_table': 'adminpanel"."Bill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.assettype')),
                ('status', models.ForeignKey(db_column='current_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'db_table': 'adminpanel"."Asset',
                'ordering': ['-created_at'],
            },
        ),
    ]
