# Generated by Django 4.2 on 2026-01-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.billcategory'),
        ),
    ]
