# Generated by Django 4.2 on 2025-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm_emp_details',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('part_of', models.CharField(choices=[('Core', 'Core'), ('Tech', 'Tech'), ('None', 'None')], max_length=20)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('TeamLead', 'Team_Lead'), ('None', 'None')], max_length=20)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'team_farm"."farm_employee_details',
            },
        ),
        migrations.CreateModel(
            name='infra_emp_details',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('part_of', models.CharField(choices=[('Core', 'Core'), ('Tech', 'Tech'), ('None', 'None')], default='None', max_length=20)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Intern', 'Intern'), ('Team_Lead', 'Team_Lead'), ('None', 'None')], default='None', max_length=20)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'team_infra"."infra_employee_details',
            },
        ),
        migrations.CreateModel(
            name='team_manage',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('MD', 'Md'), ('None', 'None')], default='None', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'team_management"."management_team',
            },
        ),
    ]
