# Generated by Django 4.2 on 2025-12-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_profile_user_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts_profile', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
