# Generated by Django 4.2 on 2025-12-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='Date',
            field=models.DateField(default=None, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts_profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
