# Generated by Django 4.2 on 2025-12-17 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_profile_branch_profile_designation_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='photo_link',
            new_name='Photo_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Brach',
            field=models.CharField(max_length=50, null=True, verbose_name='emp_branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True, verbose_name='emp_email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=50, null=True, verbose_name='emp_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('MD', 'MD'), ('TeamLead', 'TeamLead')], max_length=10, null=True, verbose_name='emp_role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Designation',
            field=models.CharField(max_length=50, null=True, verbose_name='emp_designation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Emp_id',
            field=models.ForeignKey(db_column='emp_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts_profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='emp_id'),
            preserve_default=False,
        ),
    ]
