# Generated by Django 4.2 on 2025-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm_emp_details',
            options={'verbose_name': 'Farm Employee ', 'verbose_name_plural': 'Farm Employees'},
        ),
        migrations.AlterModelOptions(
            name='infra_emp_details',
            options={'verbose_name': 'Infra Employee ', 'verbose_name_plural': 'Infra Employees'},
        ),
        migrations.AlterModelOptions(
            name='team_manage',
            options={'verbose_name': 'Management Team', 'verbose_name_plural': 'Management Teams'},
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='designation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='emp_id',
            new_name='Emp_id',
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='emp_name',
            new_name='Emp_name',
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='farm_emp_details',
            old_name='part_of',
            new_name='Part_of',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='designation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='emp_id',
            new_name='Emp_id',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='emp_name',
            new_name='Emp_name',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='infra_emp_details',
            old_name='part_of',
            new_name='Part_of',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('MD', 'MD'), ('TeamLead', 'TeamLead'), ('Inter', 'Intern')], max_length=10, null=True, verbose_name='emp_role'),
        ),
    ]
