# Generated by Django 4.2 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_farm_emp_details_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Emp_id',
            new_name='Employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='Date_of_birth',
            field=models.DateField(null=True, verbose_name='emp_date_of_birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Date_of_join',
            field=models.DateField(null=True, verbose_name='emp_date_of_joining'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True, verbose_name='emp_email_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=50, null=True, verbose_name='emp_full_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='emp_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('MD', 'MD'), ('TeamLead', 'TeamLead'), ('Intern', 'Intern')], max_length=10, null=True, verbose_name='emp_role'),
        ),
    ]
