# Generated by Django 4.2 on 2025-12-18 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_rename_emp_id_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Brach',
            new_name='Branch',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Employee_id',
            field=models.OneToOneField(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts_profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='emp_id'),
        ),
    ]
