# Generated by Django 4.2 on 2025-12-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_brach_profile_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Hr', 'Hr'), ('MD', 'Md'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('TeamLead', 'Teamlead'), ('others', 'Other')], default='others', max_length=10, verbose_name='emp_role'),
        ),
    ]
