# Generated by Django 4.2 on 2025-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='Part_of',
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='role',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='Part_of',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='role',
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='team',
            field=models.CharField(default=None, max_length=20, verbose_name='Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='team',
            field=models.CharField(default=None, max_length=20, verbose_name='Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(max_length=20, verbose_name='emp_role'),
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Role',
            field=models.CharField(default=None, max_length=20, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Role',
            field=models.CharField(default=None, max_length=20, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_manage',
            name='Role',
            field=models.CharField(default=None, max_length=20, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
