# Generated by Django 4.2 on 2025-12-23 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_remove_farm_emp_details_part_of_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employees Profile'},
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='Emp_id',
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='Emp_name',
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='File',
        ),
        migrations.RemoveField(
            model_name='farm_emp_details',
            name='team',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='Emp_id',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='Emp_name',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='File',
        ),
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='file',
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Email_id',
            field=models.CharField(default=None, max_length=50, verbose_name='email_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Employee',
            field=models.OneToOneField(db_column='Employee_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='employee_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Photo_link',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/', verbose_name='image_link'),
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Email_id',
            field=models.CharField(default=None, max_length=50, verbose_name='email_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Employee',
            field=models.OneToOneField(db_column='Employee_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='employee_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Photo_link',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/', verbose_name='image_link'),
        ),
        migrations.AddField(
            model_name='team_manage',
            name='Email_id',
            field=models.CharField(default=None, max_length=50, verbose_name='email_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_manage',
            name='Employee',
            field=models.OneToOneField(db_column='Employee_id', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='employee_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_manage',
            name='Name',
            field=models.CharField(default=None, max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_manage',
            name='Photo_link',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/', verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='farm_emp_details',
            name='Designation',
            field=models.CharField(max_length=50, null=True, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='farm_emp_details',
            name='Role',
            field=models.CharField(max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='infra_emp_details',
            name='Designation',
            field=models.CharField(max_length=50, null=True, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='infra_emp_details',
            name='Role',
            field=models.CharField(max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(max_length=50, null=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date_of_birth',
            field=models.DateField(null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date_of_join',
            field=models.DateField(null=True, verbose_name='date_of_joining'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(max_length=50, null=True, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email_id',
            field=models.EmailField(max_length=254, null=True, verbose_name='email_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Employee_id',
            field=models.OneToOneField(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounts_profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='employee_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=50, null=True, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Photo_link',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='image_link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='team_manage',
            name='Role',
            field=models.CharField(max_length=20, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='farm_emp_details',
            name='Team',
            field=models.CharField(default=None, max_length=20, verbose_name='team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infra_emp_details',
            name='Team',
            field=models.CharField(default=None, max_length=20, verbose_name='team'),
            preserve_default=False,
        ),
    ]
