# Generated by Django 4.2 on 2025-12-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_options_remove_farm_emp_details_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'designation',
                'db_table': 'team_management"."designations',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'role',
                'db_table': 'team_management"."roles',
            },
        ),
    ]
