# Generated by Django 4.2 on 2025-12-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_designation_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.SmallAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('branch_name', models.CharField(max_length=25, unique=True, verbose_name='branch')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'db_table': 'team_management"."Branches',
            },
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'designation', 'verbose_name_plural': 'designations'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
