# Generated by Django 4.2 on 2026-01-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_branch_alter_designation_options_alter_roles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infra_emp_details',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='team_manage',
            name='Employee',
        ),
        migrations.AddField(
            model_name='designation',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
        migrations.AddField(
            model_name='roles',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
        migrations.DeleteModel(
            name='farm_emp_details',
        ),
        migrations.DeleteModel(
            name='infra_emp_details',
        ),
        migrations.DeleteModel(
            name='team_manage',
        ),
    ]
