# Generated by Django 4.2 on 2026-01-05 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_infra_emp_details_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-Name'], 'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employees Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.ForeignKey(db_column='Branch', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.ForeignKey(db_column='Designation', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='accounts.designation', verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email_id',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.ForeignKey(db_column='Role', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_roles', to='accounts.roles', verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['Role', 'Designation'], name='accounts_pr_Role_1ac410_idx'),
        ),
    ]
