# Generated by Django 4.2 on 2026-01-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_profile_options_alter_profile_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.ForeignKey(db_column='Branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.ForeignKey(db_column='Designation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='accounts.designation', verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.ForeignKey(db_column='Role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_roles', to='accounts.roles', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
