# Generated by Django 4.2 on 2026-01-06 09:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_alter_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='management_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True, verbose_name='full_name')),
                ('Email_id', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email_id')),
                ('Date_of_birth', models.DateField(null=True, verbose_name='date_of_birth')),
                ('Photo_link', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='image_link')),
                ('Date_of_join', models.DateField(null=True, verbose_name='date_of_joining')),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='management', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('Role', models.ForeignKey(db_column='Role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_roles', to='accounts.roles', verbose_name='role')),
            ],
            options={
                'verbose_name': 'management_profile',
                'db_table': 'team_management"."management_profiles',
                'ordering': ['-Date_of_join', 'Role'],
            },
        ),
    ]
