# Generated by Django 4.2 on 2026-01-19 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_management_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50, unique=True)),
                ('count', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'departments',
                'db_table': 'team_management"."Departments',
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='Financial_years_Quaters_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField()),
            ],
            options={
                'db_table': 'team_management"."Financial_year_with_Quaters',
            },
        ),
        migrations.CreateModel(
            name='Quaters',
            fields=[
                ('quater', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('starting_month', models.DateField(null=True)),
                ('ending_month', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'quaters',
                'db_table': 'team_management"."Quaters',
                'ordering': ['quater'],
            },
        ),
        migrations.CreateModel(
            name='Monthly_department_head_and_subhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_the_quater', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('Meeting_head', models.CharField(max_length=100)),
                ('Sub_Head_D1', models.CharField(max_length=100, null=True)),
                ('Sub_Head_D2', models.CharField(max_length=100, null=True)),
                ('Sub_Head_D3', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, related_name='dapartment', to='accounts.departments')),
                ('quater_with_financial_year', models.ForeignKey(db_column='quater', on_delete=django.db.models.deletion.CASCADE, related_name='quater', to='accounts.financial_years_quaters_mapping')),
            ],
            options={
                'db_table': 'team_management"."Monthly_department_wise_head_and_subhead',
                'ordering': ['quater_with_financial_year'],
            },
        ),
        migrations.AddField(
            model_name='financial_years_quaters_mapping',
            name='Quater',
            field=models.ForeignKey(db_column='quater', on_delete=django.db.models.deletion.CASCADE, related_name='current_quater', to='accounts.quaters'),
        ),
    ]
