# Generated by Django 4.2 on 2026-01-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_departments_financial_years_quaters_mapping_quaters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_years_quaters_mapping',
            name='financial_year',
        ),
        migrations.AddField(
            model_name='financial_years_quaters_mapping',
            name='financial_year_end',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial_years_quaters_mapping',
            name='financial_year_start',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthly_department_head_and_subhead',
            name='meeting_sub_head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
