# Generated by Django 4.2 on 2026-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_financial_years_quaters_mapping_financial_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quaters',
            name='ending_month',
        ),
        migrations.RemoveField(
            model_name='quaters',
            name='starting_month',
        ),
        migrations.AddField(
            model_name='quaters',
            name='end_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quaters',
            name='start_month',
            field=models.IntegerField(null=True),
        ),
    ]
