# Generated by Django 4.2 on 2026-01-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_quaters_ending_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Department',
            field=models.ForeignKey(db_column='department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='accounts.departments', verbose_name='department'),
        ),
    ]
