# Generated by Django 4.2 on 2026-01-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_profile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthly_department_head_and_subhead',
            options={},
        ),
        migrations.RemoveField(
            model_name='monthly_department_head_and_subhead',
            name='quater_with_financial_year',
        ),
        migrations.AddField(
            model_name='monthly_department_head_and_subhead',
            name='quater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_head_quater', to='accounts.quaters'),
            preserve_default=False,
        ),
    ]
