# Generated by Django 4.2 on 2026-01-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_monthly_department_head_and_subhead_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financial_years_Quaters_Mapping',
        ),
    ]
