# Generated by Django 4.2 on 2026-01-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_delete_financial_years_quaters_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly_department_head_and_subhead',
        ),
        migrations.DeleteModel(
            name='Quaters',
        ),
    ]
