# Generated by Django 4.2 on 2026-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_delete_monthly_department_head_and_subhead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='full_name'),
        ),
    ]
