# Generated by Django 4.2 on 2026-01-21 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=10, unique=True, verbose_name='employee-function')),
            ],
            options={
                'verbose_name_plural': 'Functions',
                'db_table': 'team_management"."Functions',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='Teamlead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamlead', to=settings.AUTH_USER_MODEL, verbose_name='teamlead'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Function',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.functions', verbose_name='function'),
        ),
    ]
