# Generated by Django 4.2 on 2026-01-21 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_functions_profile_teamlead_profile_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Function',
            field=models.ForeignKey(db_column='function', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.functions', verbose_name='function'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Teamlead',
            field=models.ForeignKey(db_column='teamlead', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamlead', to=settings.AUTH_USER_MODEL, verbose_name='teamlead'),
        ),
    ]
