# Generated by Django 4.2 on 2026-01-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0032_alter_profile_function_alter_profile_teamlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_profile',
            name='Employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
