# Generated by Django 4.2 on 2026-02-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_management_profile_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'departments'},
        ),
    ]
