# Generated by Django 4.2 on 2026-02-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_departments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['Name'], 'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employees Profile'},
        ),
    ]
