# Generated by Django 4.2 on 2026-01-08 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('group_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='group_id')),
                ('group_name', models.CharField(blank=True, db_column='group_name', max_length=100, unique=True)),
                ('description', models.TextField(db_column='description_of_group', max_length=200, null=True, verbose_name='description')),
                ('participants', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='created_groups')),
            ],
            options={
                'verbose_name': 'Group',
                'db_table': "messaging'.'Groups",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualChats',
            fields=[
                ('chat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant1', models.ForeignKey(db_column='user1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_participant1', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='participant1')),
                ('participant2', models.ForeignKey(db_column='user2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_participant2', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='participant2')),
            ],
            options={
                'db_table': "messaging'.'UsersChats",
                'ordering': ['participant1', 'participant2'],
            },
        ),
        migrations.CreateModel(
            name='IndividualMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.PROTECT, related_name='personal_messages', to='Messaging.individualchats')),
                ('sender', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, related_name='sended_personal_messages', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': "messaging'.'chats",
                'ordering': ['chat', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='Messaging.groupchats')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_group_messages', to=settings.AUTH_USER_MODEL)),
                ('tag_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taged_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': "messaging'.'GroupMessages",
                'ordering': ['group', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('unseenmessages', models.SmallIntegerField(default=0)),
                ('groupchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='Messaging.groupchats')),
                ('participant', models.ForeignKey(db_comment='participant', on_delete=django.db.models.deletion.CASCADE, related_name='part_of_groups', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'GroupMember',
                'db_table': "messaging'.'GroupMembers",
                'ordering': ['participant', 'unseenmessages'],
            },
        ),
        migrations.AddIndex(
            model_name='individualmessages',
            index=models.Index(fields=['sender'], name="messaging'._sender_830c3f_idx"),
        ),
        migrations.AddIndex(
            model_name='individualchats',
            index=models.Index(fields=['participant1'], name="messaging'._user1_9ae5cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name='individualchats',
            unique_together={('participant1', 'participant2')},
        ),
        migrations.AddIndex(
            model_name='groupmessages',
            index=models.Index(fields=['sender'], name="messaging'._sender__4e5b4c_idx"),
        ),
        migrations.AddIndex(
            model_name='groupmembers',
            index=models.Index(fields=['participant'], name="messaging'._partici_9e53ef_idx"),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('groupchat', 'participant')},
        ),
        migrations.AddIndex(
            model_name='groupchats',
            index=models.Index(fields=['created_by'], name="messaging'._created_e264cd_idx"),
        ),
    ]
