# Generated by Django 4.2 on 2026-01-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupchats',
            new_name='Groups_created_0642e7_idx',
            old_name="messaging'._created_e264cd_idx",
        ),
        migrations.RenameIndex(
            model_name='groupmembers',
            new_name='GroupMember_partici_1d6e73_idx',
            old_name="messaging'._partici_9e53ef_idx",
        ),
        migrations.RenameIndex(
            model_name='groupmessages',
            new_name='GroupMessag_sender__edb16d_idx',
            old_name="messaging'._sender__4e5b4c_idx",
        ),
        migrations.RenameIndex(
            model_name='individualchats',
            new_name='UsersChats_user1_519126_idx',
            old_name="messaging'._user1_9ae5cb_idx",
        ),
        migrations.RenameIndex(
            model_name='individualmessages',
            new_name='Chats_sender_a22afa_idx',
            old_name="messaging'._sender_830c3f_idx",
        ),
        migrations.AlterModelTable(
            name='groupchats',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='groupmembers',
            table='GroupMembers',
        ),
        migrations.AlterModelTable(
            name='groupmessages',
            table='GroupMessages',
        ),
        migrations.AlterModelTable(
            name='individualchats',
            table='UsersChats',
        ),
        migrations.AlterModelTable(
            name='individualmessages',
            table='Chats',
        ),
    ]
