# Generated by Django 4.2 on 2026-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_rename_messaging__created_e264cd_idx_groups_created_0642e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='group_id',
            field=models.CharField(default='G00345', primary_key=True, serialize=False, verbose_name='group_id'),
        ),
        migrations.AlterField(
            model_name='individualchats',
            name='chat_id',
            field=models.CharField(default='C43995512', primary_key=True, serialize=False, verbose_name='chat_id'),
        ),
    ]
