# Generated by Django 4.2 on 2026-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_alter_groupchats_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='group_id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='group_id'),
        ),
        migrations.AlterField(
            model_name='individualchats',
            name='chat_id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='chat_id'),
        ),
    ]
