# Generated by Django 4.2 on 2026-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0004_alter_groupchats_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmessages',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
