# Generated by Django 4.2 on 2026-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0005_individualmessages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchats',
            name='last_message_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='individualchats',
            name='last_message_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
