# Generated by Django 4.2 on 2026-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0007_alter_groupmessages_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='last_message_at',
            field=models.DateField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchats',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualchats',
            name='last_message_at',
            field=models.DateField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualmessages',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
