# Generated by Django 4.2 on 2026-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0008_alter_groupchats_last_message_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchats',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
