# Generated by Django 4.2 on 2026-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0009_alter_groupchats_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchats',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='individualchats',
            options={'ordering': ['participant1', 'participant2', '-last_message_at']},
        ),
    ]
