# Generated by Django 4.2 on 2026-01-20 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0029_delete_monthly_department_head_and_subhead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quaters',
            fields=[
                ('quater', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_month', models.IntegerField(null=True)),
                ('end_month', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'quaters',
                'db_table': 'team_management"."Quaters',
                'ordering': ['quater'],
            },
        ),
        migrations.CreateModel(
            name='Monthly_department_head_and_subhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_of_the_quater', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('Meeting_head', models.CharField(max_length=100)),
                ('meeting_sub_head', models.CharField(max_length=100, null=True)),
                ('Sub_Head_D1', models.CharField(max_length=100, null=True)),
                ('Sub_Head_D2', models.CharField(max_length=100, null=True)),
                ('Sub_Head_D3', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, related_name='dapartment', to='accounts.departments')),
                ('quater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_head_quater', to='QuaterlyReports.quaters')),
            ],
            options={
                'db_table': 'team_management"."Monthly_department_wise_head_and_subhead',
            },
        ),
    ]
