# Generated by Django 4.2 on 2026-01-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0013_alter_task_options_alter_taskassignies_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuaterlyReports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('month_and_quater_id', models.ForeignKey(db_column='month_quater', on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.monthly_department_head_and_subhead')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus')),
                ('user', models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'team_management"."UserEntries',
            },
        ),
    ]
