# Generated by Django 4.2 on 2026-01-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_profile_function_alter_profile_teamlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0016_taskcreateandeditlogs_taskstatuschangelogs'),
        ('QuaterlyReports', '0002_usersentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionableGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'quatery_reports"."ActionableGoals',
                'ordering': ['FunctionGoal'],
            },
        ),
        migrations.CreateModel(
            name='GRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'quatery_reports"."GRP',
                'ordering': ['grp'],
            },
        ),
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale', models.IntegerField(null=True)),
                ('Calls', models.IntegerField(null=True)),
                ('Trial', models.IntegerField(null=True)),
                ('Demand', models.IntegerField(null=True)),
                ('Old_tgt', models.IntegerField(null=True)),
                ('New_acq', models.IntegerField(null=True)),
                ('Pitch', models.IntegerField(null=True)),
                ('CP_ratio', models.CharField(null=True)),
                ('Lead', models.IntegerField(null=True)),
                ('Qual', models.IntegerField(null=True)),
                ('Demo', models.IntegerField(null=True)),
                ('Quote', models.IntegerField(null=True)),
                ('Close', models.IntegerField(null=True)),
                ('Conversion_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grp', models.ForeignKey(db_column='grp', on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.grps', verbose_name='grp')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus', verbose_name='status')),
            ],
            options={
                'db_table': 'quatery_reports"."SalesStatistics',
                'ordering': ['grp'],
            },
        ),
        migrations.CreateModel(
            name='PlannedActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('deadline', models.DateField()),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='assigned_help_to')),
                ('grp', models.ForeignKey(db_column='grp', on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.grps', verbose_name='grp')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus', verbose_name='status')),
            ],
            options={
                'db_table': 'quatery_reports"."PlannedActions',
                'ordering': ['grp', '-deadline'],
            },
        ),
        migrations.CreateModel(
            name='FunctionsGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maingoal', models.CharField(max_length=100)),
                ('Function', models.ForeignKey(db_column='function_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.functions', verbose_name='function_id')),
            ],
            options={
                'db_table': 'quatery_reports"."FunctionGoals',
                'ordering': ['Function'],
            },
        ),
        migrations.CreateModel(
            name='FunctionsEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('Creator', models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('goal', models.ForeignKey(db_column='sub_goal_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.actionablegoals')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus')),
            ],
            options={
                'db_table': 'quatery_reports"."FunctionsEntries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='actionablegoals',
            name='FunctionGoal',
            field=models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.functionsgoals'),
        ),
    ]
