# Generated by Django 4.2 on 2026-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuaterlyReports', '0003_actionablegoals_grps_salesstatistics_plannedactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionablegoals',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
