# Generated by Django 4.2 on 2026-02-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuaterlyReports', '0004_alter_actionablegoals_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionsentries',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='plannedactions',
            options={},
        ),
        migrations.RemoveField(
            model_name='plannedactions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='plannedactions',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='plannedactions',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='plannedactions',
            name='grp',
        ),
        migrations.RemoveField(
            model_name='plannedactions',
            name='status',
        ),
        migrations.AddField(
            model_name='actionablegoals',
            name='grp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.grps'),
        ),
        migrations.AddField(
            model_name='functionsentries',
            name='time',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='plannedactions',
            table=None,
        ),
    ]
